language: node_js
cache:
  directories:
    - node_modules
    - ~/.npm
node_js:
  - '12'
git:
  depth: 3
script:
  - yarn build
notifications:
  email:
    recipients:
      - ja.vega.g10@gmail.com
      - julian.vega@uao.edu.co
    on_success: always
    on_failure: always
  slack: practicetravisci:f7Yph80c76XhpYxYnqBOxkfV
deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/
  target_branch: gh-pages
  commit_message: "Project Deploy"
  on:
    branch: master